// GENERATED from the frozen labeling artifacts:
//   SEED_ROWS    <- app/src/test/resources/fixtures/phase0_route_labels.jsonl
//                   (Phase 0 live Jev labeling of the seed corpus)
//   DEVICE_ROWS  <- app/src/test/resources/fixtures/phase3_device_labels.jsonl
//                   (Phase 3 device-corpus labels, hand-assigned per plan B2;
//                    regex_action from the real baseline, Jev fields null)
// Regenerate with: python tools/jev_harness/gen_kotlin_fixture.py
// Do not hand-edit.
package com.vyze.app.agent.student

/**
 * Frozen route labels consumed by StudentRouterFixtureTest.
 *
 * SEED_ROWS backs the Phase 2→3 gate (student ≥ regex baseline on the
 * Jev-labeled seed corpus) and the Jev-teacher reference test.
 *
 * DEVICE_ROWS is the B2 regression gate for the v2 distilled branches
 * (app-cue echo, greeting garble, ms deictic opener): `expected` was
 * hand-assigned from the device-corpus distillation evidence; `note`
 * records the source row. DEVICE_ROWS carries no Jev fields by design.
 */
object StudentRouterFixture {

    data class Row(
        val id: String,
        val lang: String,
        val query: String,
        val previous: String?,
        val expected: String,
        val regexAction: String,
        val jevAction: String?,
        val jevConfidence: Double?,
        val jevFastPathNoul: Double?,
        val note: String?,
    )

    val SEED_ROWS: List<Row> = listOf(
        Row(
            id = "p1",
            lang = "en",
            query = "What does this medicine label say?",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.48,
            note = null,
        ),
        Row(
            id = "p2",
            lang = "en",
            query = "Describe the entire room in front of me.",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.05,
            note = null,
        ),
        Row(
            id = "p3",
            lang = "en",
            query = "Is the door on my left or right?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.95,
            jevFastPathNoul = 0.1,
            note = null,
        ),
        Row(
            id = "p4",
            lang = "en",
            query = "Give me a double tap vibration.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "none_of_these",
            jevConfidence = 0.45,
            jevFastPathNoul = 0.92,
            note = null,
        ),
        Row(
            id = "p5",
            lang = "en",
            query = "Help, I fell down and need assistance!",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.94,
            jevFastPathNoul = 0.39,
            note = null,
        ),
        Row(
            id = "e1",
            lang = "en",
            query = "Read this letter for me.",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.68,
            note = null,
        ),
        Row(
            id = "e2",
            lang = "en",
            query = "What color is this shirt?",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.38,
            note = null,
        ),
        Row(
            id = "e3",
            lang = "en",
            query = "Is it dark in here?",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.77,
            note = null,
        ),
        Row(
            id = "e4",
            lang = "en",
            query = "What is in front of me?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
            note = null,
        ),
        Row(
            id = "e5",
            lang = "en",
            query = "Play some music.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.85,
            note = null,
        ),
        Row(
            id = "e6",
            lang = "en",
            query = "How much money is this banknote?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.59,
            note = null,
        ),
        Row(
            id = "a1",
            lang = "en",
            query = "Is someone standing near me?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.08,
            note = null,
        ),
        Row(
            id = "a2",
            lang = "en",
            query = "Can you tell what this fruit is?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.87,
            jevFastPathNoul = 0.06,
            note = null,
        ),
        Row(
            id = "a3",
            lang = "en",
            query = "Is this the exit sign?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.46,
            jevFastPathNoul = 0.41,
            note = null,
        ),
        Row(
            id = "a4",
            lang = "en",
            query = "Is my bus number showing on that board?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.85,
            jevFastPathNoul = 0.39,
            note = null,
        ),
        Row(
            id = "a5",
            lang = "en",
            query = "Does this look spoiled?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.93,
            jevFastPathNoul = 0.13,
            note = null,
        ),
        Row(
            id = "a6",
            lang = "en",
            query = "Is there a chair I can sit on?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.91,
            jevFastPathNoul = 0.07,
            note = null,
        ),
        Row(
            id = "a7",
            lang = "en",
            query = "Check if this bill is a fifty.",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.86,
            jevFastPathNoul = 0.66,
            note = null,
        ),
        Row(
            id = "m1",
            lang = "ms",
            query = "Baca label ubat ini.",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.61,
            note = null,
        ),
        Row(
            id = "m2",
            lang = "ms",
            query = "Apa warna baju ini?",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.41,
            note = null,
        ),
        Row(
            id = "m3",
            lang = "ms",
            query = "Gelap ke di sini?",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.75,
            note = null,
        ),
        Row(
            id = "m4",
            lang = "ms",
            query = "Apa kat depan saya?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.12,
            note = null,
        ),
        Row(
            id = "m5",
            lang = "ms",
            query = "Ada orang dekat dengan saya ke?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.11,
            note = null,
        ),
        Row(
            id = "m6",
            lang = "ms",
            query = "Nota ini berapa ringgit?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.39,
            note = null,
        ),
        Row(
            id = "m7",
            lang = "ms",
            query = "Adakah buah ini masak?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.96,
            jevFastPathNoul = 0.19,
            note = null,
        ),
        Row(
            id = "m8",
            lang = "ms",
            query = "Pintu tu di kiri atau kanan saya?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.82,
            jevFastPathNoul = 0.13,
            note = null,
        ),
        Row(
            id = "m9",
            lang = "ms",
            query = "Putar lagu sikit.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.81,
            note = null,
        ),
        Row(
            id = "m10",
            lang = "ms",
            query = "Tolong, saya jatuh! Saya tak boleh bangun.",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.92,
            jevFastPathNoul = 0.48,
            note = null,
        ),
        Row(
            id = "ma1",
            lang = "ms",
            query = "Papan tanda tu tulis apa?",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.52,
            note = null,
        ),
        Row(
            id = "ma2",
            lang = "ms",
            query = "Boleh tak you tengok jalan ni ada kereta?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.06,
            note = null,
        ),
        Row(
            id = "z1",
            lang = "zh",
            query = "帮我读一读这个药瓶上的标签。",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.52,
            note = null,
        ),
        Row(
            id = "z2",
            lang = "zh",
            query = "这件衣服是什么颜色？",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.95,
            jevFastPathNoul = 0.3,
            note = null,
        ),
        Row(
            id = "z3",
            lang = "zh",
            query = "这里是不是很暗？",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.76,
            note = null,
        ),
        Row(
            id = "z4",
            lang = "zh",
            query = "我面前是什么？",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
            note = null,
        ),
        Row(
            id = "z5",
            lang = "zh",
            query = "有人站在我旁边吗？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.09,
            note = null,
        ),
        Row(
            id = "z6",
            lang = "zh",
            query = "这张钞票是多少钱？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.5,
            note = null,
        ),
        Row(
            id = "z7",
            lang = "zh",
            query = "这水果熟了没有？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.96,
            jevFastPathNoul = 0.16,
            note = null,
        ),
        Row(
            id = "z8",
            lang = "zh",
            query = "放一首歌来听。",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.82,
            note = null,
        ),
        Row(
            id = "z9",
            lang = "zh",
            query = "救命，我摔倒了，起不来！",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.52,
            note = null,
        ),
        Row(
            id = "f1",
            lang = "en",
            query = "What is in front of me?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
            note = null,
        ),
        Row(
            id = "f2",
            lang = "en",
            query = "What about this?",
            previous = "What is in front of me?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.9,
            jevFastPathNoul = 0.12,
            note = null,
        ),
        Row(
            id = "f3",
            lang = "ms",
            query = "Apa kat depan saya?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.11,
            note = null,
        ),
        Row(
            id = "f4",
            lang = "ms",
            query = "Bagaimana dengan ini?",
            previous = "Apa kat depan saya?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.82,
            jevFastPathNoul = 0.18,
            note = null,
        ),
        Row(
            id = "f5",
            lang = "zh",
            query = "我面前是什么？",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.11,
            note = null,
        ),
        Row(
            id = "f6",
            lang = "zh",
            query = "那这个呢？",
            previous = "我面前是什么？",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.75,
            jevFastPathNoul = 0.15,
            note = null,
        ),
        Row(
            id = "f7",
            lang = "en",
            query = "And this one?",
            previous = "What color is this shirt?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.83,
            jevFastPathNoul = 0.38,
            note = null,
        ),
        Row(
            id = "f8",
            lang = "ms",
            query = "Yang ini pula?",
            previous = "Apa warna baju ini?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.55,
            jevFastPathNoul = 0.22,
            note = null,
        ),
        Row(
            id = "f9",
            lang = "zh",
            query = "这个呢？",
            previous = "这件衣服是什么颜色？",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.72,
            jevFastPathNoul = 0.28,
            note = null,
        ),
        Row(
            id = "f10",
            lang = "ms",
            query = "Yang ini juga baca.",
            previous = "Baca label ubat ini.",
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.5,
            note = null,
        ),
        Row(
            id = "f11",
            lang = "en",
            query = "Read this one too.",
            previous = "What does this medicine label say?",
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.39,
            note = null,
        ),
        Row(
            id = "n1",
            lang = "en",
            query = "",
            previous = null,
            expected = "IGNORE",
            regexAction = "IGNORE",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.37,
            note = null,
        ),
        Row(
            id = "n2",
            lang = "ms",
            query = "errr... aaa...",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.59,
            note = null,
        ),
    )

    val DEVICE_ROWS: List<Row> = listOf(
        Row(
            id = "dev1",
            lang = "en",
            query = "what is in front of me",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_1: canonical scene opener; regex fallthrough",
        ),
        Row(
            id = "dev2",
            lang = "ms",
            query = "Ini pula apa ini pula apa",
            previous = "Hey, I'm about this.",
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 vm_16: v2 ms deictic opener branch (Jev 0.65)",
        ),
        Row(
            id = "dev3",
            lang = "en",
            query = "please say that again",
            previous = "what is in front of me",
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_2: v2 app-cue echo branch; answered with a stale scene before v2",
        ),
        Row(
            id = "dev4",
            lang = "en",
            query = "Hello, I'm a model.",
            previous = "is in front of me analyzing what is in front of me",
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_13: v2 greeting-garble branch (Jev 0.79)",
        ),
        Row(
            id = "dev5",
            lang = "en",
            query = "Hey, I'm about this.",
            previous = "Hello, I'm a model.",
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_14: v2 greeting-garble branch (Jev 0.75); no question content",
        ),
        Row(
            id = "dev6",
            lang = "en",
            query = "is in front of me analyzing what is in front of me",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_12: app-cue garble hybrid (mic caught 'Analyzing' plus a scene opener); previous was a tap-lane prompt (boilerplate omitted). KNOWN STUDENT MISS: embeds 'what is in front' so the student says SCENE — motivating row for the v3 app-cue-garble branch",
        ),
        Row(
            id = "dev7",
            lang = "en",
            query = "you read this for me",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_6: read intent via legacy keyword; previous was a tap-lane prompt (boilerplate omitted)",
        ),
        Row(
            id = "dev8",
            lang = "en",
            query = "is this a drinking water",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_4: product verification ask; previous was a tap-lane prompt (boilerplate omitted)",
        ),
        Row(
            id = "dev9",
            lang = "en",
            query = "is it recyclable",
            previous = "you read this for me",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789950997064 ir_7: follow-up on the just-read object; catch-all",
        ),
        Row(
            id = "dev10",
            lang = "en",
            query = "are you sure",
            previous = "and what is behind it",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789815166971 ir_2: challenge follow-up; the app answers these from the live scene, never IGNORE",
        ),
        Row(
            id = "dev11",
            lang = "en",
            query = "and what is behind it",
            previous = "what is in front of me",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789815166971 vm_3: spatial follow-up; catch-all (deliberately not SCENE: it points at a target rather than a broad describe)",
        ),
        Row(
            id = "dev12",
            lang = "en",
            query = "what about this",
            previous = "is that a refrigerator",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789815166971 ir_5: follow-up echo trap; seed f2 analog from real usage",
        ),
        Row(
            id = "dev13",
            lang = "en",
            query = "but it looks like refrigerator",
            previous = "are you sure",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789815166971 ir_3: user correction; catch-all",
        ),
        Row(
            id = "dev14",
            lang = "en",
            query = "is that a refrigerator",
            previous = "but it looks like refrigerator",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session 1789815166971 ir_4: verification question; catch-all",
        ),
        Row(
            id = "dev15",
            lang = "en",
            query = "what is this",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "sessions ...68400 ir_36 / ...614 ir_50: canonical en object-ID opener; must stay routable (catch-all contract)",
        ),
        Row(
            id = "dev16",
            lang = "en",
            query = "how about this",
            previous = "what is this",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...68400 ir_37 (repeats as ir_44): follow-up echo trap with previous-answer context; catch-all",
        ),
        Row(
            id = "dev17",
            lang = "en",
            query = "in front of me",
            previous = "how about this",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...68400 ir_45: bare scene fragment without question word; catch-all VQ is today's correct serve",
        ),
        Row(
            id = "dev18",
            lang = "en",
            query = "what color is the dough",
            previous = "is there a refrigerator",
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...68400 ir_49: color ask on non-product object; live run hit the native color fast path",
        ),
        Row(
            id = "dev19",
            lang = "en",
            query = "is there a person",
            previous = "in front of me",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...68400 ir_46: presence ask (person); needs full scene reasoning, not fast path",
        ),
        Row(
            id = "dev20",
            lang = "en",
            query = "is there a refrigerator",
            previous = "clothing line",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...68400 ir_48: presence ask (refrigerator); catch-all",
        ),
        Row(
            id = "dev21",
            lang = "en",
            query = "Hello, I'm a student. Read the label for me. Read the",
            previous = "Hello, hello. Hello.",
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...614 ir_57: greeting garble + real read intent — read keywords must win before v2 greeting-garble branch",
        ),
        Row(
            id = "dev22",
            lang = "en",
            query = "Hello, hello. Hello.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...614 ir_56: doubled greeting garble (the live pre-gate test form, ms-tagged by ASR); v2 greeting-garble branch",
        ),
        Row(
            id = "dev23",
            lang = "en",
            query = "what is in front of me",
            previous = "inipula APA",
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = null,
            jevConfidence = null,
            jevFastPathNoul = null,
            note = "session ...614 ir_52: canonical scene ask; SCENE opener contract",
        ),
    )

    /** Actions whose speech-routing correctness the gate measures. */
    val GATE_ACTIONS = setOf(
        "VLM_SCENE_DESCRIBE", "VLM_TEXT_READ", "VLM_VOICE_QUERY",
        "FAST_COLOR_ANALYSIS", "LIGHT_CHECK", "SOS", "IGNORE",
    )
}
